version: '3'
services:
  victim:
    build: .
    hostname: victim
    command: /sbin/init
    privileged: true
    networks:
      vpcbr:
        ipv4_address: 10.10.0.2

  attacker:
    build: .
    hostname: attacker
    command: /sbin/init
    privileged: true
    networks:
      vpcbr:
        ipv4_address: 10.10.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: "10.10.0.0/24"
